### ISSUE TITLE
[FavoriteMedia]: fake dead media / broken thumbnail

### ISSUE THREAD

**Issue by EquinoxRevolt** [Dastan21/BDAddons#192]
### Discord Build

Stable

### Discord Version

Stable 179882 (d4bc856)

### Plugin Version

1.7.2

### Steps To Reproduce

N/A

### Describe the bug

In any of the tabs gif favorites, video, or image, most of the time the thumbnail will disappear with a file and an x which i assume means dead media as this has happened to me before and i would just have to remove it, but upon clicking the preview video or clicking on a gif it works just fine, and im confused whether this is a thumbnail issue or if discord thinks it is dead media.

### Screenshots

video: https://www.kapwing.com/videos/640b9a5d9b027c001e357e74

**Comment by Dastan21** [comment]
Can you provide the link of the media uploaded in the video pls?

**Comment by EquinoxRevolt** [comment]
here you go, just a quick note i forgot to mention. sometimes the dead media or broken thumbnail will disappear in case that means anything. https://cdn.discordapp.com/attachments/906674206094290955/1057941109847887882/trim.925D7D8C-82F7-4C47-8D12-A53457B2783C.mp4

**Comment by Aezaeo** [comment]
I have a similar thing but on my end its just an empty blue canvas. For gifs specifically, the ones Ive tested dont work when opened in browser. Mine are dead links from gfycat. Here's an example link: [https://gfycat.com/idealpositivegull](url)

**Comment by venturedied** [comment]
I have dozens of gifs with Xs over them.
![image](https://user-images.githubusercontent.com/72032133/226198111-12a05993-aa15-45e9-9814-047f93814891.png)
This is one of them. https://media.discordapp.net/attachments/930490786276057198/1006621581650428056/caption-30.gif

**Comment by Dastan21** [comment]
Fixed in 1.8.0

**Comment by Dastan21** [comment]
Send your config.json

**Comment by Dastan21** [comment]
[FavoriteMedia.config.txt](https://github.com/Dastan21/BDAddons/files/11617001/FavoriteMedia.config.txt)

and refavorite those:
- https://cdn.discordapp.com/attachments/1030547377112760340/1078853017513771118/FpvlArJagAAzQwt.png
- https://cdn.discordapp.com/attachments/857762124703727636/1077693089218576545/IMG_2808.png
- https://cdn.discordapp.com/attachments/1027063867353866271/1083583840704020480/image0.png

**Comment by AidanPlayz3310** [comment]
Well refavoriting those 3 images fixed my images tab, so that's good. But for some reason the video tab is still the same. I even thought I was being smart by opening the file and changing ""dead": true" to ""dead": false" for all of them thinking that it labeled all of them dead by accident, but that didn't do anything. after a restart it changed them all back to ""dead": true" anyways. another thing to note is when I try to open a dropdown in the config menu inside BD it doesn't show anything except for the first one. 
![Discord_i0zgtLQLHl](https://github.com/Dastan21/BDAddons/assets/67774956/b058a554-ad01-4e53-807c-cfd4ab6d1990)
Dont know if that would be related to the issue I'm having.

**Comment by Dastan21** [comment]
The settings issue has been reported here #202.
And about the dead medias, idk why they fail to load... worked fine on my end with your config.json

**Comment by AidanPlayz3310** [comment]
well, I was able to fix it by sending all of the broken-looking but working videos in some blank dm, unfavoriting them, then refavoriting them. don't know how they broke to begin with but it seems good now
